# Generated by Django 5.1.1 on 2024-10-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jahan_news_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
