# Generated by Django 5.1.1 on 2024-10-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jahan_news_portal', '0002_alter_newsmodel_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='comments',
            field=models.PositiveIntegerField(),
        ),
    ]
