# Generated by Django 5.1.1 on 2024-10-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jahan_news_portal', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsModel',
        ),
    ]
