# Generated by Django 5.1.1 on 2024-10-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jahan_news_portal', '0008_newsmodel_approved_commentnewsmodel_replycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
