# Generated by Django 5.1.1 on 2024-10-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jahan_news_portal', '0009_alter_newsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentnewsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
